# Generated by Django 3.2.8 on 2021-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leave',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
